language: node_js
node_js:
  - "6"

jdk:
  - oraclejdk8

addons:
  sonarcloud: true
  
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=un-acarreo -Dsonar.projectKey=UN-Acarreo_Backend -Dsonar.sources='./server' -X
