language: node_js
node_js: 12.13.0

jdk:
  - oraclejdk8

addons:
  sonarcloud: true

script:
  - sudo apt-get update
  - sudo apt-get install postgresql postgresql-contrib
  - sudo su - postgres
  - createdb UN-Acarreo
  #- psql "CREATE USER postgres WITH PASSWORD 'admin';"
  #- psql 
  # - \q
  - cd server
  - npm i
  - npm install nyc --save-dev
  - npm install --save-dev mocha
  - npm i -D chai
  - npm install --save-dev jsdom
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN_4 -Dsonar.organization=un-acarreo -Dsonar.projectKey=UN-Acarreo_Backend -Dsonar.sources='' -X
