language: node_js
node_js: 12.13.0

jdk:
  - oraclejdk8

services:
  - postgresql

addons:
  sonarcloud: true

before_script:
  - psql -c "CREATE USER postgres WITH ENCRYPTED PASSWORD 'admin';"
  - psql -c 'create database "UN-Acarreo";' -U postgres

script:
  - cd server
  - npm i
  - npm install nyc --save-dev
  - npm install --save-dev mocha
  - npm i -D chai
  - npm install --save-dev jsdom
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN_4 -Dsonar.organization=un-acarreo -Dsonar.projectKey=UN-Acarreo_Backend -Dsonar.sources='' -X
