language: node_js
node_js: 12.13.0

jdk:
  - oraclejdk8

addons:
  sonarcloud: true

script:
  - cd server
  - npm i
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN_4 -Dsonar.organization=un-acarreo -Dsonar.projectKey=UN-Acarreo_Backend -Dsonar.sources='./server' -X
